spring.profiles.active: development
logging.level.org.springframework.cloud.kubernetes: DEBUG
message: hello my name is Gunal
management.server.port: 8081
---
spring.profiles: development
message: hello my name is gunal
---
spring.profiles: kubernetes
message: hello kubernetes
